edition = "2018"
# format_doc_comments = true
# format_macro_matchers = true
# match_block_trailing_comma = true
# merge_imports = true
newline_style = "Unix"
# normalize_comments = true
# overflow_delimited_expr = true
# reorder_impl_items = true
use_small_heuristics = "Max"
use_try_shorthand = true
