[package]
name = "anytime-rs"
version = "0.1.0"
authors = ["M@ Dunlap <matthew.dunlap+anytime@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/dunmatt/anytime-rs"

[dependencies]
log = "0.4.8"
